//////////////////          ////////////////
////                              //
///                              //
//                              //
//                             //
//                            //
///                          //
//////////////// HEAT SHEE  //

SYNTHS

bubbles: rl, start, end, rate

azBarg: amp rl, freq, rate, dec, out

narcodesample: buf, here, there, rate, rl

ejk: amp, rl, at, out

resonate: amp, rl, f1, f2, f3

drums: amp, out

sampler: amp, rate, rl, pos, out

booty_k: amp, freq, fmod, rl, out

pad1000: amp, freq, cf, rate, lf, out

bs1000: amp, freq, rt, out

